---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "common.names.fullname" . }}
  labels:
    {{- include "common.labels" $ | nindent 4 }}
stringData:
  {{- include "authentik.secrets" (dict "root" $ "values" $.Values.authentik) | indent 2 }}